# Generated by Django 3.2.4 on 2021-06-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20210614_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='github_url',
        ),
    ]
